# Generated by Django 4.2.15 on 2024-09-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txwake', '0002_emailsubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsubscription',
            old_name='subscribed_on',
            new_name='date_subscribed',
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
